version: '3'
services:
# services:
  # db:
  #   image: mysql:8.0
  #   container_name: db
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     - MYSQL_DATABASE=wordpress
  #   volumes:
  #     - type: bind
  #       source: /var/lib/efs/mysql
  #       target: /var/lib/mysql
  #   command: '--default-authentication-plugin=mysql_native_password'
  #   networks:
  #     - app-network

  joomla:
    image: joomla
    container_name: joomla
    restart: always
    env_file: .env
    links:
      - databaseuas.c1fvmon0yhsk.us-east-1.rds.amazonaws.com:3306
    environment:
      - JOOMLA_DB_HOST=$MYSQL_DB
      - JOOMLA_DB_USER=$MYSQL_USER
      - JOOMLA_DB_PASSWORD=$MYSQL_PASSWORD
      - JOOMLA_DB_NAME=joomla_docker
    volumes:
      - type: bind
        source: /var/lib/uascloud
        target: /var/www/html
    networks:
      - app-network
    
    webserver:
      depends_on:
        - joomla
      image: nginx:1.15.12-alpine
      container_name: webserver
      restart: always
      ports:
        - "80:80"
      volumes:
        - /var/lib/uascloud:/var/www/html
        - ./nginx-conf:/etc/nginx/conf.d
        # - certbot-etc:/etc/letsencrypt
      networks:
        - app-network

  # certbot:
  #   depends_on:
  #     - webserver
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - /var/lib/efs/wordpress:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email mishael.elian@ti.ukdw.ac.id --agree-tos --no-eff-email -d wordpres-finalcloud-815283555.us-east-1.elb.amazonaws.com

# volumes:
  # certbot-etc:
  # wordpress:
  # dbdata:

networks:
  app-network:
    driver: bridge


  # wordpress:
  #   # depends_on:
  #   #   - db
  #   image: wordpress:5.1.1-fpm-alpine
  #   container_name: wordpress
  #   restart: always
  #   env_file: .env
  #   environment:
  #     - WORDPRESS_DB_HOST=$MYSQL_DB
  #     - WORDPRESS_DB_USER=$MYSQL_USER
  #     - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
  #     - WORDPRESS_DB_NAME=wordpress_docker
  #   volumes:
  #     - type: bind
  #       source: /var/lib/uascloud
  #       target: /var/www/html
  #   networks:
  #     - app-network

  #   networks:
  #    app-network:
  #    driver: bridge

  # certbot:
  #   depends_on:
  #     - webserver
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - /var/lib/efs/wordpress:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email mishael.elian@ti.ukdw.ac.id --agree-tos --no-eff-email -d wordpres-finalcloud-815283555.us-east-1.elb.amazonaws.com

# volumes:
  # certbot-etc:
  # wordpress:
  # dbdata:

# networks:
#   app-network:
#     driver: bridge